const mongoose = require("mongoose");

const gameAttemptSchema = new mongoose.Schema(
  {
    // RewardTransaction -> GameAttempt relationship
    // Represents the transaction generated by this attempt (if any)
    transactionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "RewardTransaction",
      default: null,
    },
    // Keep userId for quick queries to find attempts by user
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    gameName: {
      type: String,
      required: true,
      trim: true,
    },
    status: {
      type: String,
      enum: ["started", "completed", "failed", "abandoned"],
      default: "started",
    },
    durationSeconds: {
      type: Number,
      default: 0,
      min: 0,
    },
  },
  { timestamps: true }
);

// Indexes
gameAttemptSchema.index({ userId: 1 });
gameAttemptSchema.index({ transactionId: 1 });

module.exports = mongoose.model("GameAttempt", gameAttemptSchema);
